import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {getFirestore,doc,getDoc,collection,getDocs,query,where,limit,addDoc,updateDoc,deleteDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){$("msg").textContent=e.message;$("msg").className="error"}};
$("logout").onclick=()=>signOut(auth);$("closePanel").onclick=()=>$("panel").classList.add("hidden");
onAuthStateChanged(auth,async u=>{ $("login").classList.toggle("hidden",!!u);$("dash").classList.toggle("hidden",!u);if(!u)return;$("user").textContent=u.email||"";try{let s=await getDoc(doc(db,"users",u.uid));if(!s.exists()){$("status").innerHTML='<span class="error">⚠️ users document not found.</span>';return}let d=s.data(),r=String(d.role||"").trim().toLowerCase();$("status").textContent="Role: "+r;if(r==="admin"){$("dashTitle").textContent="Super Admin Dashboard";$("admin").classList.remove("hidden");wire()}else if(r==="parent"){$("dashTitle").textContent="Parent Dashboard";$("parent").classList.remove("hidden");renderParent(d.studentNumber)}else if(r==="teacher")$("teacher").classList.remove("hidden")}catch(e){$("status").innerHTML='<span class="error">Firestore error: '+esc(e.message)+'</span>'}});
function wire(){document.querySelectorAll("#admin [data-section]").forEach(b=>b.onclick=()=>open(b.dataset.section))}
async function open(s){$("panel").classList.remove("hidden");$("panelTitle").textContent=s;let snap=await getDocs(collection(db,s));$("panelBody").innerHTML="<p>"+snap.size+" record(s).</p>"+(snap.empty?"":"<table><tr><th>Data</th></tr>"+snap.docs.map(d=>"<tr><td>"+esc(JSON.stringify(d.data()))+"</td></tr>").join("")+"</table>")}
async function renderParent(no){$("parentBody").innerHTML="<p><b>Student Number:</b> "+esc(no)+"</p><div class='grid'><button data-p='profile'>👤 Profile</button><button data-p='attendance'>📅 Attendance</button><button data-p='studyRecords'>📖 Study</button><button data-p='results'>🏆 Results</button><button data-p='notices'>📢 Notices</button><button data-p='leaveRequests'>📝 Leave</button></div><div id='parentView' class='panel'></div>";document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>parentView(b.dataset.p,no));parentView("profile",no)}
async function parentView(s,no){let q=collection(db,s),snap;if(s==="notices")snap=await getDocs(q);else{let field="studentNumber";snap=await getDocs(query(q,where(field,"==",no)))}$("parentView").innerHTML="<h4>"+esc(s)+"</h4>"+(snap.empty?"<p>No records found.</p>":"<pre>"+esc(snap.docs.map(d=>JSON.stringify(d.data(),null,2)).join("\n\n"))+"</pre>")}
